### ISSUE TITLE
Value fails for custom lists in humidity slider

### ISSUE THREAD

**Issue by badrobot15** [kherel/flutter_fun#2]
Played around and updated the list value in humidity_config.dart. The math seems to fail with different lists. How can this be made dynamic to accept any minVal, maxVal and list? Or did I miss something

**Comment by kherel** [comment]
Hi, thanks for your interest.
When I started to implement current design I didn't notice that the measurement steps not equal. 0, 10, 25, 30, 35, 40, 45, 50, 75, 100. 

..So at the begining I added start and begining, but afterward I noticed, that equal only working space.

That is why everything like that. 
My idea was only to copy design.
